#ifndef MERCURY_STANDARD_SYNTAX_HEADER_FILE
#define MERCURY_STANDARD_SYNTAX_HEADER_FILE

#ifndef STANDARD_SYNTAX
#define STANDARD_SYNTAX
#endif

STANDARD_SYNTAX const char* LET_S = "LET";
STANDARD_SYNTAX const char* LOOP_S = "LOOP";
STANDARD_SYNTAX const char* FUNCTION_S = "FUNC";
STANDARD_SYNTAX const char* RETURN_S = "RETURN";
STANDARD_SYNTAX const char* DO_S = "DO";
STANDARD_SYNTAX const char* END_S = "END";
STANDARD_SYNTAX const char* IF_S = "IF";
STANDARD_SYNTAX const char* AND_S = "AND";
STANDARD_SYNTAX const char* OR_S = "OR";
STANDARD_SYNTAX const char* NOT_S = "NOT";
STANDARD_SYNTAX const char* ELSE_S = "ELSE";
STANDARD_SYNTAX const char* FOR_S = "FOR";
STANDARD_SYNTAX const char* IS_S = "IS";
STANDARD_SYNTAX const char* IN_S = "IN";
STANDARD_SYNTAX const char* WHILE_S = "WHILE";
STANDARD_SYNTAX const char* BREAK_S = "BREAK";
STANDARD_SYNTAX const char* CONTINUE_S = "CONTINUE";
STANDARD_SYNTAX const char* CONST_S = "CONST";
STANDARD_SYNTAX const char* STATIC_S = "STATIC";
STANDARD_SYNTAX const char* GLOBAL_S = "GLOBAL";
STANDARD_SYNTAX const char* LOCAL_S = "LOCAL";
STANDARD_SYNTAX const char* STRING_S = "STRING";
STANDARD_SYNTAX const char* STR_S = "STRING";
STANDARD_SYNTAX const char* INCLUDE_S = "INCLUDE";
STANDARD_SYNTAX const char* CLASS_S = "CLASS";
STANDARD_SYNTAX const char* INTERFACE_S = "INTERFACE";
STANDARD_SYNTAX const char* STRUCT_S = "STRUCT";
STANDARD_SYNTAX const char* NEW_S = "NEW";
STANDARD_SYNTAX const char* LIST_S = "LIST";
STANDARD_SYNTAX const char* DELETE_S = "DELETE";
STANDARD_SYNTAX const char* CAST_S = "CAST";
STANDARD_SYNTAX const char* FLOAT_S = "FLOAT";
STANDARD_SYNTAX const char* DOUBLE_S = "DOUBLE";
STANDARD_SYNTAX const char* CHAR_S = "CHAR";
STANDARD_SYNTAX const char* SHORT_S = "SHORT";
STANDARD_SYNTAX const char* LONG_S = "LONG";
STANDARD_SYNTAX const char* AUTO_S = "AUTO";
STANDARD_SYNTAX const char* VOID_S = "VOID";
STANDARD_SYNTAX const char* THEN_S = "THEN";
STANDARD_SYNTAX const char* BOOL_S = "BOOL";

#endif // MERCURY_STANDARD_SYNTAX_HEADER_FILE